### ISSUE TITLE
Postinstall hook (scripts/copy-deps.js) is failing to find Shell.js dependency

### ISSUE THREAD

**Issue by impinball** [ArthurClemens/Polythene#8]
Shell.js is used in the postinstall hook, but is listed as a `devDependency` in the package.json folder, and thus is not installing on my machine before the hook is called.

Here's the actual output I get (excluding NPM noise):

```
> node scripts/copy-deps.js

module.js:338
    throw err;
    ^

Error: Cannot find module 'shelljs/global'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/isiah/tmp/node_modules/polythene/scripts/copy-deps.js:3:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

**Comment by ArthurClemens** [comment]
With the splitting up of the codebase into polythene and polythene-examples, the copy script is no longer used.
